### PR TITLE
FIX: Pandas deprecations

### LINKED ISSUE #160: Deprecated pandas usage in `get-all` and in `get-ids-from-query`
Pandas removed `DataFrame.append` and the `squeeze` parameter from `pd.read_csv` as of v2.0 ([source](https://pandas.pydata.org/docs/whatsnew/v2.0.0.html#removal-of-prior-version-deprecations-changes)). Consequently, the methods `get-all` and `get-ids-from-query` both fail with the current minimal conda installation instructions (using q2-fondue from the channel "https://packages.qiime2.org/qiime2/2023.2/tested/" and pandas v2.0.3). 

The following error occurs when running `get-all`:
```
AttributeError: 'DataFrame' object has no attribute 'append'
```

And when running `get-ids-from-query` this error occurs:
```
TypeError: read_csv() got an unexpected keyword argument 'squeeze'
```
Note: When using q2-fondue from the channels "2023.5/tested" or "2023.7/tested" pandas v1.5.3 is installed and no errors are raised.

**Suggested fix:**
To make q2-fondue forward compatible with pandas v2.0 and still usable with pandas version <2.0: 
* replace `.append()` with recommended `.concat()`
* update usage of squeeze with [DataFrame.squeeze](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.squeeze.html) after reading in.

### PR DESCRIPTION
**Pull request by adamovanja**
This PR ensures forward compatibility with pandas v2.0 and maintains usablility with pandas version <2.0. It fixes #160.

**Note on testing:**
The below test should fail when installing q2-fondue from channel "https://packages.qiime2.org/qiime2/2023.2/tested/" as currently described in the main channel `README.md` file (and done in the Docker image). The test works without errors when using the updated code.       
Using q2-fondue from channel "https://packages.qiime2.org/qiime2/2023.7/tested/" the code works independently (code from main channel or this PR).

* Follow the instructions to install the minimal conda environment in the `README.md` file.
* Fetch both sequence and metadata for a defined accession ID (e.g. test A below) and/or fetch accession IDs from a query of your choice.

Test A:
```
echo -e "id\nERR1698166" > file.tsv
qiime tools import  \
	--type NCBIAccessionIDs  \
	--input-path file.tsv  \
	--output-path file.qza
qiime fondue get-all  \
	--i-accession-ids file.qza  \
	--p-email your_email@somewhere.com  \
	--p-retries 0  \
	--output-dir file-output  \
	--verbose
```

**Note before merging**
- [x] Before merging this PR, we should update the Docker image and the link in the README.

### CODE REVIEW

File: README.md [hunk 1]
```diff
@@ -65,9 +67,9 @@ vdb-config --proxy <your proxy URL> --proxy-disable no
 Use containerization to integrate q2-fondue into your pipelines, or simply run reproducibly without the need for heavyweight package managers. [Read more about Docker here.](https://www.docker.com/get-started/)
  
 * Install [Docker](https://docs.docker.com/engine/install/) with the linked instructions
-* Pull the [q2-fondue Docker image](https://hub.docker.com/layers/linathekim/q2-fondue/2023.2/images/sha256-214d0575eb4eaf435c5c4a7d29edf0fc082e47999b884b52a173f2ec469975f2?context=repo):
+* Pull the [q2-fondue Docker image](https://hub.docker.com/layers/linathekim/q2-fondue/2023.7/images/<UPDATEDLINKHERE>):
```
Comment (lina-kim) [inline README.md:70]:
```suggestion
* Pull the [q2-fondue Docker image](https://hub.docker.com/layers/linathekim/q2-fondue/2023.7/images/sha256-f5d26959ac035811a8f34e2a46f6cc381f9a4ce21b3604a196c1ee176ba708e7?context=repo):
```

**Review by lina-kim — COMMENTED** [review]
How interesting! Thanks for looking into and resolving this @adamovanja. Docker image has been updated and runs successfully. 

Just wondering, how come the 2023.9 tag of q2-fondue is filed under the 2023.7 QIIME 2 release according to the package directory?

**Comment by adamovanja** [comment]
thanks for the updated Docker image @lina-kim.

As for your tag-release question, I think @misialq is the better source to answer this question since he has kindly kept track of Q2 releases and tags for now.
